$vm_cpus = 2
$vm_memory = 2048

Vagrant.configure("2") do |config|
    config.vm.box = "rockylinux/9"
    config.vm.box_version = "6.0.0"

    config.ssh.insert_key = false
    config.ssh.forward_agent = true

    if Vagrant.has_plugin? 'vagrant-vbguest'
        config.vbguest.auto_update = false
    end

    config.vm.provider :virtualbox do |vb|
        vb.gui = false
        vb.cpus = $vm_cpus
        vb.memory = $vm_memory
    end
end

# $vm_cpus = 1
# $vm_memory = 1024

# Vagrant.configure("2") do |config|
#   config.vm.box = "minimal/trusty64"

#   config.ssh.insert_key = false
#   config.ssh.forward_agent = true

#   config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true

#   config.vm.synced_folder ".", "/vagrant", disabled: true

#   if Vagrant.has_plugin? 'vagrant-vbguest'
#     config.vbguest.auto_update = false
#   end

#   config.vm.provider :virtualbox do |vb|
#     vb.customize ["modifyvm", :id, "--usb", "on"]
#     vb.customize ["modifyvm", :id, "--usbehci", "off"]

#     vb.gui = false
#     vb.cpus = $vm_cpus
#     vb.memory = $vm_memory
#     vb.check_guest_additions = false
#     vb.functional_vboxsf = false
#   end
# end