# Requirements:
# Vagrant provisioner downloaded
# Some plugins: 
#   1. vagrant-disksize

Vagrant.configure("2") do |config|
    config.vm.box = "#{ENV['vm_os_image']}"
    config.vm.box_version = "#{ENV['vm_os_image_version']}"

    config.disksize.size = "#{ENV['vm_diskstorage_size']}"

    config.ssh.insert_key = false
    config.ssh.forward_agent = true

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.network "public_network", bridge: "#{ENV['vm_network_interface']}"
  
    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
            echo #{ssh_pub_key} > /home/vagrant/.ssh/authorized_keys
            echo #{ssh_pub_key} > /root/.ssh/authorized_keys
        SHELL
    end
    
    config.vm.provider :virtualbox do |vb|
        vb.gui = false
        vb.cpus = ENV['vm_cpus']
        vb.memory = ENV['vm_memory']
    end
    
    for master_index in (1..ENV['vm_masters_count'].to_i)
        config.vm.define "masternode-#{master_index}" do |masternode|
            masternode.vm.hostname = "masternode-#{master_index}"
            # masternode.vm.cpus = ENV['vm_cpus'].to_i * 2
            # masternode.vm.memory = ENV['vm_memory'].to_i * 2
        end
    end

    for worker_index in (1..ENV['vm_workers_count'].to_i)
        config.vm.define "workernode-#{worker_index}" do |workernode|
            workernode.vm.hostname = "workernode-#{worker_index}"
        end
    end

    for db_index in (1..ENV['vm_dbs_count'].to_i)
        config.vm.define "database-#{db_index}" do |database|
            database.vm.hostname = "databasenode-#{db_index}"
        end
    end
end