# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerhub-registry-connection: connect-profile-dockerhub
  dockerhub-repo: luverk1d/dotnet-project-for-altenar

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: luver-pool
    steps:
    - task: Docker@2
      displayName: Login into docker account
      inputs:
        command: login
        containerRegistry: $(dockerhub-registry-connection)

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/todolistAltenar/backend/dockerfile'
        repository: ${dockerhub-repo}
        tags: |
          $(tag)