FROM node:24-alpine AS build
WORKDIR /app/
# EXPOSE 5173

# add all dependencies
COPY /frontend/package.json/ ./frontend/
COPY /frontend/package-lock.json/ ./frontend/

# download all dependencies
RUN npm install ./frontend/

# get all files
COPY /frontend/ ./frontend/

# build app
WORKDIR /app/frontend/
RUN npm run build -c Release

# use new image to publish
FROM node:24-alpine AS final
COPY --from=build /app/frontend/dist ./dist
COPY --from=build /app/frontend/node_modules ./node_modules

RUN npm install -g serve

ENTRYPOINT ["serve", "-s", "dist", "-p", "5173"]