FROM node:24 AS build
WORKDIR /app/
# EXPOSE 5173

# add all dependencies
COPY ./package.json/ ./frontend/
COPY ./package-lock.json/ ./frontend/

# download all dependencies
RUN npm install ./frontend/

# get all files
COPY . ./frontend/

# build app
WORKDIR /app/frontend/
RUN npm run build -c Release

# use new image to publish
FROM node:24-alpine AS final
COPY --from=build /app/frontend/dist ./dist

RUN npm install -g serve

ENTRYPOINT ["serve", "-s", "dist", "-p", "5173"]