---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-configure
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.240-192.168.0.250
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-configure
  namespace: metallb-system
spec:
  ipAddressPools:
  - metallb-configure
