---
# tasks file for start_application_database

## Проверить существует ли /var/lib/postgresql/
- name: Copy docker compose for db
  ansible.posix.synchronize:
    src: /home/{{ jumphost_user }}/todolistProjectForAltenar/todolistAltenar/docker-compose.db.yml
    dest: /home/{{ ansible_ssh_user }}/docker-compose.yml
  delegate_to: '{{ jumphost_ip }}'

- name: Docker compose up db
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_ssh_user }}
    state: present