---
# tasks file for start_application_backend
- name: Create dir backend
  ansible.builtin.file:
    path: /home/{{ ansible_ssh_user }}/backend
    state: directory
    mode: '0755'

- name: Copy docker image
  ansible.posix.synchronize:
    src: /home/{{ jumphost_user }}/todolistProjectForAltenar/todolistAltenar/backend/dockerfile.tar
    dest: /home/{{ ansible_ssh_user }}/backend/dockerfile.tar
  delegate_to: '{{ jumphost_ip }}'

- name: Image docker load
  community.docker.docker_image_load:
    path: /home/{{ ansible_ssh_user }}/backend/dockerfile.tar
    use_ssh_client: true
  register: result

- name: Copy docker compose backend
  ansible.posix.synchronize:
    src: /home/{{ jumphost_user }}/todolistProjectForAltenar/todolistAltenar/docker-compose.backend.yml
    dest: /home/{{ ansible_ssh_user }}/docker-compose.yml
  delegate_to: '{{ jumphost_ip }}'

- name: Docker compose up backend
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_ssh_user }}
    state: present
  register: docker_compose_debug

- name: Debug show
  ansible.builtin.debug:
    msg: '{{ docker_compose_debug }}'
