---
# tasks file for login-into-accs
- name: Gh login into Github
  ansible.builtin.shell: echo '{{ gh_token }}' | gh auth login --git-protocol https --hostname GitHub.com --with-token
  when: inventory_hostname in groups['jump-hosts']
  register: debug_gh_auth

- name: Debug show
  debug: 
    msg: '{{ debug_gh_auth }}'