---
# tasks file for login-into-accs
- name: Gh login into Github
  shell: gh auth login --git-protocol https --hostname GitHub.com --with-token <<< '{{ gh_token }}'
  when: inventory_hostname in groups['jump-hosts']