---
# tasks file for login-into-accs
- name: Gh login into Github
  ansible.builtin.shell: echo '{{ gh_token }}' | gh auth login --git-protocol ssh --hostname GitHub.com --with-token
  when: inventory_hostname in groups['jump-hosts']
  register: debug_gh_auth

# - name: Debug show
#   debug: 
#     msg: '{{ debug_gh_auth }}'

- name: Docker login
  community.docker.docker_login:
    username: '{{ docker_login }}'
    password: '{{ docker_password }}'
    reauthorize: true
  when: inventory_hostname in groups['master-nodes'] or inventory_hostname in groups['jump-hosts']
  register: debug_docker_auth

# - name: Debug show
#   debug: 
#     msg: '{{ debug_docker_auth }}'