---
# tasks file for start_application_frontend
- name: Update project files
  ansible.builtin.git:
    repo: '{{ git_repo }}'
    dest: '{{ dest }}'
    version: main
  register: project_files_updated

- name: Actions if project files update
  when: project_files_updated.changed == true
  block:
    - name: Remove images backend and frontend
      community.docker.docker_image:
        name: '{{ item }}'
        tag: latest
        state: absent
      loop:
        - '{{ backend_image_name }}'
        - '{{ frontend_image_name }}'
      ignore_errors: true

    - name: Build backend image
      community.docker.docker_image:
        name: '{{ backend_image_name }}'
        tag: latest
        build:
          path: '{{ dest }}/todolistAltenar/backend/'
        source: build
      register: image_build_backend_res

    - name: Build frontend image
      community.docker.docker_image:
        name: '{{ frontend_image_name }}'
        build:
          path: '{{ dest }}/todolistAltenar/frontend/'
        source: build
      register: image_build_frontend_res

    - name: Save backend image
      community.docker.docker_image_export:
        name: '{{ backend_image_name }}'
        path: '{{ dest }}/todolistAltenar/backend/dockerfile.tar'
      when: image_build_backend_res.failed == False 

    - name: Save frontend image
      community.docker.docker_image_export:
        name: '{{ frontend_image_name }}'
        path: '{{ dest }}/todolistAltenar/frontend/dockerfile.tar'
      when: image_build_frontend_res.failed == False

    - name: Create new tag
      community.builtin.shell: git tag -a {{ git_deploy_tag }} -m {{ git_deploy_tag_message }}

    - name: Add new tag to repo
      community.builtin.shell: git push origin {{ git_deploy_tag }}