---
# tasks file for start_application_frontend
- name: Update project files
  ansible.builtin.git:
    repo: '{{ git_repo }}'
    dest: '{{ dest }}'
    version: main
  register: project_files_updated

- name: Actions if project files update
  when: project_files_updated.changed == true
  block:
    - name: Remove all images + cache
      community.docker.docker_prune:
        images: true
        builder_cache: true
        images_filters:
          dangling: false
      register: debug_message_remove

    - name: Build backend image
      community.docker.docker_image:
        name: '{{ backend_image_name }}'
        tag: latest
        build:
          path: '{{ dest }}/todolistAltenar/backend/'
          nocache: true
        source: build
      register: backend_build_reg

    - name: Build frontend image
      community.docker.docker_image:
        name: '{{ frontend_image_name }}'
        build:
          path: '{{ dest }}/todolistAltenar/frontend/'
          nocache: true
        source: build
      register: frontend_build_reg

    - name: debug show
      ansible.builtin.debug:
        msg: '{{ backend_build_reg }} |||| {{ frontend_build_reg }}'

    - name: Save backend image
      community.docker.docker_image_export:
        name: '{{ backend_image_name }}'
        path: '{{ dest }}/todolistAltenar/backend/dockerfile.tar'

    - name: Save frontend image
      community.docker.docker_image_export:
        name: '{{ frontend_image_name }}'
        path: '{{ dest }}/todolistAltenar/frontend/dockerfile.tar'