apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: "in-cluster"
    namespace: default
  source:
    repoURL: https://github.com/Arnfourm/todolistProjectForAltenar.git
    targetRevision: HEAD
    path: todolistAltenar/argocd-apps/applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false