apiVersion: v1
kind: PersistentVolume
metadata:
  name: hashicorp-vault-pv
  namespace: hashicorp-vault
spec:
  volumeMode: Filesystem
  capacity: 
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/vault/data/"