---
- name: Download apps
  hosts: database-hosts:backend-hosts:frontend-hosts:jump-hosts
  become: true

  tasks:      
  - name: Install git
    ansible.builtin.dnf:
      name: git
      state: present
    when: inventory_hostname in groups['jump-hosts']

  - name: Install repo docker
    ansible.builtin.command: "dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo"
  
  - name: Install docker
    ansible.builtin.dnf:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin 
        - docker-compose-plugin
      state: present
  
  - name: Update && upgrade
    ansible.builtin.dnf:
      name: "*"
      state: latest
      update_cache: yes

  - name: Starting docker daemon
    ansible.builtin.systemd_service:
      name: docker
      enabled: true
      state: started

  - name: Create new group for docker
    ansible.builtin.group:
      name: docker
      state: present

  - name: Add user to group docker
    ansible.builtin.user:
      name: luver
      groups: luver,docker
      state: present
      append: true
    register: add_to_docker_group

  - name: Check
    ansible.builtin.debug:
      msg: '{{ add_to_docker_group || add_to_docker_group.changed }}'

  - name: Reboot server
    ansible.builtin.reboot:
    when: add_to_docker_group.changed == true