---
- name: Download docker
  hosts: linuxSystems
  become: true

  tasks:
  - name: Install repo docker
    ansible.builtin.command: "dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo"
  
  - name: Install docker
    ansible.builtin.dnf:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin 
        - docker-compose-plugin
      state: present
  
  - name: Update && upgrade
    ansible.builtin.dnf:
      name: "*"
      state: latest
      update_cache: yes