---
- name: Download apps
  hosts: database-hosts:backend-hosts:frontend-hosts:jump-hosts
  become: true
  
  roles:
    - { role: dowload_git, when: inventory_hostname in groups['jump-hosts'] }
    - docker_dowload
    - update_everything