---
- name: Simple tool for starting host
  hosts: linuxSystems

  tasks:
  - name: Download python
    become: true
    ansible.builtin.dnf:
      name: "*"
      state: latest
      update_cache: yes
