---
- name: General settings for all servers
  hosts: all
  become: true

  roles:
    - role: general_settings_to_start_server

# - name: Configuration server for k8s
#   hosts: master-nodes:worker-nodes
#   become: true

#   roles:
#     - role: configure_server_for_k8s

# - name: Install all needs apps for each server
#   hosts: all
#   become: true

#   roles:
#     - role: download_apps