---
- name: Start backend service
  hosts: backend-hosts
  vars:
      jumphost_user: luver
  
  tasks:
  - name: Create dir backend
    ansible.builtin.file:
      path: /home/{{ ansible_ssh_user }}/backend
      state: directory
      mode: '0755'

  - name: Copy docker image
    ansible.builtin.copy:
      src: /home/{{ jumphost_user }}/todolistProjectForAltenar/todolistAltenar/backend/dockerfile.tar
      dest: /home/{{ ansible_ssh_user }}/backend/dockerfile.tar

  - name: Image docker load
    community.docker.docker_image_load:
      path: /home/{{ ansible_ssh_user }}/backend/dockerfile.tar
      use_ssh_client: true
    register: result

  - name: Copy docker compose backend
    ansible.builtin.copy:
      src: /home/{{ jumphost_user }}/todolistProjectForAltenar/todolistAltenar/docker-compose.backend.yml
      dest: /home/{{ ansible_ssh_user }}/docker-compose.yml
    
  - name: Docker compose up backend
    community.docker.docker_compose_v2:
      project_src: /home/{{ ansible_ssh_user }}
      state: present