---
- name: Start app from jumphost (build dockerfiles and etc. for NOW)
  hosts: jump-hosts
  vars:
    git_repo: https://github.com/Arnfourm/todolistProjectForAltenar
    dest: /home/{{ ansible_user }}/ 

  tasks:
  - name: Update project files
    ansible.builtin.git:
      repo: '{{ git_repo }}'
      dest: '{{ dest }}'
      