---
- name: Simple tool for starting host
  hosts: linuxSystems

  tasks:
  - name: Download python
    become: true
    ansible.builtin.raw: dnf install python3 python3-pip

  - name: Update && upgrade
    become: true
    ansible.builtin.dnf:
      name: "*"
      state: latest
      update_cache: yes