---
- name: Start todolist app
  hosts: database-hosts

  tasks:
  - name: Copy docker compose for db
    ansible.builtin.copy:
      src: ~/todolistProjectForAltenar/todolistAltenar/docker-compose.db.yml
      dest: /home/"{{ansible_ssh_user}}"/docker-compose.db.yml

  - name: Docker compose up db
    community.docker.docker_compose_v2:
      project_src: /home/"{{ansible_ssh_user}}"/docker-compose.db.yml
      state: present