---
- name: Start application jumphost
  hosts: jump-hosts
  roles:
    - role: start_application_jumphost
      vars: 
        git_deploy_tag: v1.3
        git_deploy_tag_message: Test deploy to check variable from playbook to role

- name: Start application database
  hosts: database-hosts
  roles:
    - role: start_application_database

- name: Start application backend
  hosts: backend-hosts
  serial: 1
  any_errors_fatal: true
  roles:
    - role: start_application_backend

- name: Start applcation frontend
  hosts: frontend-hosts
  roles:
    - role: start_application_frontend