---
- name: Start/restart whole application
  hosts: database-hosts:backend-hosts:frontend-hosts:jump-hosts

  roles:
    - role: start_application_jumphost
      when: inventory_hostname in groups['jump-hosts']

    - role: start_application_database
      when: inventory_hostname in groups['database-hosts']

    - role: start_application_backend
      when: inventory_hostname in groups['backend-hosts']

    - role: start_application_frontend
      when: inventory_hostname in groups['frontend-hosts']