---
# tasks file for docker_dowload
- name: Install repo docker
  ansible.builtin.command: "dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo"
  
- name: Install docker
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: present

- name: Starting docker daemon
  ansible.builtin.systemd_service:
    name: docker
    enabled: true
    state: started

- name: Create new group for docker
  ansible.builtin.group:
    name: docker
    state: present

- name: Add user to group docker
  ansible.builtin.user:
    name: '{{ ansible_ssh_user }}'
    groups: '{{ ansible_ssh_user }},docker'
    state: present
    append: true
  register: add_to_docker_group

- name: Reboot server
  ansible.builtin.reboot:
  when: add_to_docker_group.changed == true