services:
  todolist.nginx:
    image: nginx:alpine3.22
    ports:
      - 80:80
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - todolistApp

  todolistFrontend:
    image: todolistfrontendimage
    container_name: todolistfrontend
    build:
      context: ./frontend/
      dockerfile: ./dockerfile
    ports:
      - "5173:5173"
    networks:
      - todolistApp

networks:
  todolistApp: