services:
  todolist.API:
    image: altenar-todolist-backend-image
    container_name: altenar-todolist-backend
    build:
      context: ./backend/
      dockerfile: ./dockerfile
    ports:
      - "5140:5140"
      - "5141:5141"
    environment:
      - ConnectionStrings_todolistDbContext:USER ID=luverov;Password=123456789;Host=192.168.0.110;Port=5432;Database=todolistDB;
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - todolistApp

networks:
  todolistApp: