services:
  todolist.nginx:
    image: nginx:alpine3.22
    container_name: altenar-todolist-nginx
    ports:
      - 80:80
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - todolistApp

  todolistFrontend:
    image: altenar-todolist-frontend-image
    container_name: altenar-todolist-frontend
    build:
      context: ./frontend/
      dockerfile: ./dockerfile
    ports:
      - "5173:5173"
    networks:
      - todolistApp

networks:
  todolistApp: