services:
  todolist.db:
    image: postgres:17.5-alpine3.22
    container_name: todolist_postgres_db
    environment:
      POSTGRES_DB: "todolistDB"
      POSTGRES_USER: "luverov"
      POSTGRES_PASSWORD: "123456789"
    volumes:
      - postgres:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U luverov -d todolistDB"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - 5432:5432
    networks:
      - todolistApp

volumes:
  postgres:

networks:
  todolistApp: