services:
  postgres:
    container_name: todolist_postgres_db
    image: postgres
    environment:
      POSTGRES_DB: "todolistDB"
      POSTGRES_USER: "luverov"
      POSTGRES_PASSWORD: "123456789"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres: