services:
  todolist.API:
    image: todolistimage
    container_name: todolistapi
    build:
      context: ./backend/
      dockerfile: ./dockerfile
    ports:
      - "5140:5140"
      - "5141:5141"
    environment:
      - DB_HOST=192.168.0.108
      - DB_PORT=5432
    # to use swaagger 
    #   - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - todolistApp

networks:
  todolistApp: