services:
  todolist.API:
    image: todolistimage
    container_name: todolistapi
    build:
      context: ./backend/
      dockerfile: ./dockerfile
    ports:
      - "5140:5140"
      - "5141:5141"
    environment:
      - ConnectionStrings_todolistDbContext:USER ID=luverov;Password=123456789;Host=192.168.0.108;Port=5432;Database=todolistDB;
    # to use swaagger 
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - todolistApp

networks:
  todolistApp: