apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-pod
  template:
    metadata:
      labels:
        app: backend-pod
    spec:
      containers:
      - name: altenar-todolist-backend
        image: luverk1d/todolistproject:backend-image
        imagePullPolicy: Always
        ports:
        - containerPort: 5140
        env:
        - name: ConnectionStrings__todolistDbContext
          valueFrom:
            secretKeyRef:
              name: db-connection
              key: connection-string
