apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-pod
  template:
    metadata:
      labels:
        app: frontend-pod
    spec:
      containers:
      - name: altenar-todolist-frontend
        image: luverk1d/todolistproject:frontend-image
        imagePullPolicy: Always
        ports:
          - containerPort: 5173
