apiVersion: app/v1
kind: deployment
metadata:
  name: frontend-deploy
  labels:
    app: frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: altenar-todolist-frontend
        image: altenar-todolist-frontend-image
        ports:
          - containerPort: 5173