apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: "in-cluster"
    namespace: backend-space
  source:
    repoURL: https://github.com/Arnfourm/todolistProjectForAltenar.git
    targetRevision: HEAD
    path: todolistAltenar/helm-charts/deploy-app
    helm:
      releaseName: deploy-backend
      valueFiles:
      - values-backend.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
