apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy-frontend.fullname" . }}
  labels:
    {{- include "deploy-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerport }}
      protocol: TCP
  selector:
    {{- include "deploy-frontend.selectorLabels" . | nindent 4 }}
